Added tagging and renaming.

diff --git a/audiosplit b/audiosplit
--- a/audiosplit
+++ b/audiosplit
@@ -21,6 +21,7 @@
 # A copy of the full GNU General Public Licence can be found at: 
 # http://www.gnu.org/licenses/ 
 
+shopt -s nullglob
 e_badargs=65
 e_notfound=127
 error=1
@@ -128,7 +129,7 @@ fi
 audiofile="${pathname}/${audiofile}"
 cuefile="${pathname}/${cuefile}"
 echo "Splitting audio file: $audiofile"
-echo "as per the cue file: $cuefile"
+echo ".....as per cue file: $cuefile"
 
 # Change working directory to make output appear where audio file is stored:
 cwd=`pwd`
@@ -136,10 +137,25 @@ cd "${pathname}" || exit $?
 
 # Finally, we get to the job at hand, splitting the audio file:
 if [[ -f "${audiofile}" && -f "${cuefile}" ]]; then
-  echo "Splitting..."
   cuebreakpoints "${cuefile}" | shnsplit -a "Track " -o "${format}" "${audiofile}" || exit $?
-#  echo "Tagging..."
-#  cuetag "${cuefile}" "Track*.${format}" || exit $?
+  echo "Tagging..."
+  # find . -name "Track*" -print0 | xargs -0 cuetag "$cuefile"
+  tracks=("Track*")
+  if (( ${#tracks[*]} )); then
+    cuetag "$cuefile" $tracks || exit $?
+  else
+    echo "ERROR: Tracks to be tagged disappeared after being split."
+  fi
+  echo "Renaming..."
+  find . -name "Track*" -print0 | xargs -0 lltag --yes --no-tagging --rename '%n - %t'
+  # if (( ${#tracks[*]} )); then
+  #   for track in ${tracks[@]}; do
+  #     lltag --yes --no-tagging --rename '%n - %t' "${track}" || exit $?
+  #   done
+  # fi
+  # else
+  #   echo "ERROR: Tracks to be renamed disappeared after being tagged."
+  # fi
   echo "Done."
 else
   echo "ERROR: Files to be split disappeared after being found."
